repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.3
    hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_validate
    - id: terraform_docs
      args:
        - --args=--output-file README.md